---
#apiVersion: batch/v1  # use this once on on k8s 1.21
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudflare-dns-updater
  namespace: cloudflare-dns-updater-staging
  labels:
    app: cloudflare-dns-updater
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    metadata:
      namespace: cloudflare-dns-updater-staging
      labels:
        app: cloudflare-dns-updater
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 180
      template:
        metadata:
          namespace: cloudflare-dns-updater-staging
          labels:
            app: cloudflare-dns-updater
        spec:
          serviceAccountName: cloudflare-dns-updater-sa
          imagePullSecrets:
            - name: ameelio-registry
          containers:
          - name: cloudflare-dns-updater
            image: registry.digitalocean.com/ameelio-registry/cloudflare-dns-updater:${RELEASE_VERSION}
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: cloudflare-dns-updater-config
              - secretRef:
                  name: cloudflare-dns-updater-secrets
          restartPolicy: Never

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-dns-updater-config
  namespace: cloudflare-dns-updater-staging
  labels:
    app: cloudflare-dns-updater
data:
  HOSTNAME: 'cvh-staging'
  DOMAIN: 'ameelio.org'
  ZONE_ID: 'c82786df7abd35eb6773c67960fba8d3'
